# [ [1, 1],
# [1, 2], [2, 1],
# [3, 1], [1, 3],
# [2, 2], [4, 1], [1, 4],
# [5, 1], [1, 5], 
# [1, 6], [6, 1], 
# [7, 1], [1, 7], 
# [4, 2], [2, 4], [1, 8], [8, 1], 
# [1, 9], [3, 3], [9, 1], 
# [6, 2], [2, 6], 
# [2, 8], [8, 2], [4, 4], 
# [3, 6], [6, 3], 
# [10, 2], [2, 10], 
# [12, 2], [2, 12], 
# [5, 5], 
# [3, 9], [9, 3], 
# [2, 14], [14, 2], 
# [4, 8], [2, 16], [8, 4], [16, 2], 
# [12, 3], [3, 12], [18, 2], [2, 18], [6, 6]]
train_processors: {
  sft: {type: 'DocNewMultiScaleSFTProcessor', image_size: 224, 
        anchors: [[1, 1], [1, 2], [2, 1], [1, 3], [3, 1], [1, 4], [2, 2], [4, 1], [1, 5], [5, 1], [1, 6], [2, 3], [3, 2], [6, 1], [1, 7], [7, 1], [1, 8], [2, 4], [4, 2], [8, 1], [1, 9], [3, 3], [9, 1], [1, 10], [2, 5], [5, 2], [10, 1], [1, 11], [11, 1], [2, 6], [3, 4], [4, 3], [6, 2], [2, 7], [7, 2], [3, 5], [5, 3], [2, 8], [4, 4], [8, 2], [2, 9], [3, 6], [6, 3], [9, 2], [2, 10], [4, 5], [5, 4], [10, 2]]}
}

valid_processors: {
  sft: {type: 'DocNewMultiScaleSFTProcessor', image_size: 224,
        anchors: [[1, 1], [1, 2], [2, 1], [1, 3], [3, 1], [1, 4], [2, 2], [4, 1], [1, 5], [5, 1], [1, 6], [2, 3], [3, 2], [6, 1], [1, 7], [7, 1], [1, 8], [2, 4], [4, 2], [8, 1], [1, 9], [3, 3], [9, 1], [1, 10], [2, 5], [5, 2], [10, 1], [1, 11], [11, 1], [2, 6], [3, 4], [4, 3], [6, 2], [2, 7], [7, 2], [3, 5], [5, 3], [2, 8], [4, 4], [8, 2], [2, 9], [3, 6], [6, 3], [9, 2], [2, 10], [4, 5], [5, 4], [10, 2]]}
}

data_files: [
  'ureader_json/train.jsonl',
  'ureader_json/val.jsonl'
]
# 654840

patch_pos_embed_type: post

